version: '3.8'

services:
  shipnlogic_backend:
    build: .
    command: bash -c 'while !</dev/tcp/shipnlogic_db/5432; do sleep 1; done; alembic upgrade head; uvicorn app.main:app --host 0.0.0.0 --port 8000'
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=supersecretkey
      - HASHING_ALGORITHM=HS256
      - POSTGRES_DATABASE_URL=postgresql://shipnlogic:backend@shipnlogic_db:5432/shipnlogic_db
    depends_on:
      - shipnlogic_db
    networks:
      - shipnlogic_network

  shipnlogic_db:
    image: postgres:15-alpine
    volumes:
      - shipnlogic_volume:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=shipnlogic
      - POSTGRES_PASSWORD=backend
      - POSTGRES_DB=shipnlogic_db
    networks:
      - shipnlogic_network

volumes:
  shipnlogic_volume:


networks:
  shipnlogic_network: